FROM python:3.12.5-bullseye

ARG DB_URI
ARG JWT_KEY
ARG AZURE_CONNECTION_STRING
ARG AZURE_BLOB_CONTAINER_USUARIOS
ARG AZURE_BLOB_CONTAINER_RECLAMACOES
ARG AZURE_BLOB_URL
ARG PORT
ARG EMAIL
ARG SENHA
ARG GOOGLE_API_KEY
ARG PONTOS_RECLAMACAO
ARG PONTOS_COMENTARIO
ARG PONTOS_CURTIDA
ARG DIAS_JOB

ENV DB_URI=${DB_URI}
ENV JWT_KEY=${JWT_KEY}
ENV AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
ENV AZURE_BLOB_CONTAINER_USUARIOS=${AZURE_BLOB_CONTAINER_USUARIOS}
ENV AZURE_BLOB_CONTAINER_RECLAMACOES=${AZURE_BLOB_CONTAINER_RECLAMACOES}
ENV AZURE_BLOB_URL=${AZURE_BLOB_URL}
ENV PORT=${PORT}
ENV EMAIL=${EMAIL}
ENV SENHA=${SENHA}
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
ENV PONTOS_RECLAMACAO=${PONTOS_RECLAMACAO}
ENV PONTOS_COMENTARIO=${PONTOS_COMENTARIO}
ENV PONTOS_CURTIDA=${PONTOS_CURTIDA}
ENV DIAS_JOB=${DIAS_JOB}

WORKDIR /usr/src/app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./app.py" ]
