"""tabela reclamacao

Revision ID: 467bd0a507d9
Revises: b275beeff90b
Create Date: 2024-10-18 20:36:58.470837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "467bd0a507d9"
down_revision: Union[str, None] = "b275beeff90b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("denuncia", "reclamacao")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("reclamacao", "denuncia")
    # ### end Alembic commands ###
