"""curtida

Revision ID: 5221ead91a91
Revises: e3ee465dbc55
Create Date: 2024-10-24 00:11:08.844704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5221ead91a91'
down_revision: Union[str, None] = 'e3ee465dbc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curtida',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('modificacao', sa.DateTime(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('reclamacao_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['reclamacao_id'], ['reclamacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'reclamacao_id', name='_usuario_reclamacao_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curtida')
    # ### end Alembic commands ###
