"""comentario

Revision ID: 5814bfb3fa96
Revises: 5221ead91a91
Create Date: 2024-10-28 22:19:22.890798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5814bfb3fa96'
down_revision: Union[str, None] = '5221ead91a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('modificacao', sa.DateTime(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('reclamacao_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['reclamacao_id'], ['reclamacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    # ### end Alembic commands ###
