"""tabela denuncia

Revision ID: 951fd4d564ad
Revises: d45ea5a0f6a9
Create Date: 2024-09-03 20:05:02.238017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951fd4d564ad'
down_revision: Union[str, None] = 'd45ea5a0f6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('denuncia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('modificacao', sa.DateTime(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.Enum('via', 'calcada', 'iluminacao', 'lixo', 'carro', 'sinalizacao', 'outros', name='categoria'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero_endereco', sa.String(length=200), nullable=True),
    sa.Column('ponto_referencia', sa.String(length=200), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=200), nullable=False),
    sa.Column('longitude', sa.String(length=200), nullable=False),
    sa.Column('fotos', sa.String(length=2000), nullable=False),
    sa.Column('qtd_curtidas', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denuncia')
    # ### end Alembic commands ###
