"""recuperar senha

Revision ID: b275beeff90b
Revises: 8cb720b30fa9
Create Date: 2024-10-14 21:59:45.559468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b275beeff90b'
down_revision: Union[str, None] = '8cb720b30fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recuperar_senha',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=False),
    sa.Column('modificacao', sa.DateTime(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recuperar_senha')
    # ### end Alembic commands ###
