"""coluna foto

Revision ID: cc9dd19f2bc6
Revises: d089be63636a
Create Date: 2024-09-13 22:47:53.663835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9dd19f2bc6'
down_revision: Union[str, None] = 'd089be63636a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto')
    # ### end Alembic commands ###
