"""geography

Revision ID: cd0aec5849f5
Revises: 2608ba054d2b
Create Date: 2024-10-22 00:29:31.654703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cd0aec5849f5'
down_revision: Union[str, None] = '2608ba054d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reclamacao', 'geom', nullable=False, new_column_name='geog', type_=geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geography', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reclamacao', 'geog', nullable=False, new_column_name='geom', type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), postgresql_using='geog::geometry(Point,4326)')
    # ### end Alembic commands ###
