"""remove titulo

Revision ID: d089be63636a
Revises: 3aa8ba825965
Create Date: 2024-09-12 22:45:45.073260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd089be63636a'
down_revision: Union[str, None] = '3aa8ba825965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('denuncia', 'titulo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('denuncia', sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
