"""tabela usuario

Revision ID: d45ea5a0f6a9
Revises:
Create Date: 2024-08-27 21:23:08.126710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45ea5a0f6a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('criacao', sa.DateTime(), nullable=False, default=sa.func.now()),
                    sa.Column('modificacao', sa.DateTime(), nullable=False, default=sa.func.now()),
                    sa.Column('delete', sa.Boolean(), nullable=False, default=False),
                    sa.Column('nome', sa.String(length=200), nullable=False),
                    sa.Column('email', sa.String(length=200), nullable=False),
                    sa.Column('senha', sa.String(length=200), nullable=False),
                    sa.Column('endereco', sa.String(length=200), nullable=False),
                    sa.Column('numero_endereco', sa.String(length=200), nullable=False),
                    sa.Column('complemento_endereco', sa.String(length=200), nullable=False),
                    sa.Column('cep', sa.String(length=20), nullable=False),
                    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
                    sa.Column('pontucao', sa.BigInteger(), nullable=False, default=0),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
