"""campos de localizacao not null

Revision ID: e3ee465dbc55
Revises: cd0aec5849f5
Create Date: 2024-10-23 21:56:10.771442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3ee465dbc55'
down_revision: Union[str, None] = 'cd0aec5849f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reclamacao', 'numero_endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reclamacao', 'bairro',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reclamacao', 'cidade',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('reclamacao', 'estado',
               existing_type=postgresql.ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='estado'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reclamacao', 'estado',
               existing_type=postgresql.ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', name='estado'),
               nullable=True)
    op.alter_column('reclamacao', 'cidade',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reclamacao', 'bairro',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reclamacao', 'numero_endereco',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
