name: midnight jobs
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  midnight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run jobs
        env:
          DB_URI: ${{ secrets.DB_URI }}
        run: |
          python jobs.py
